config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root 'home#index'

  resources :projects
  resources :users, only: [:index]
  resources :users do
    member do
      patch 'update_role'
    end
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :user
  belongs_to :project
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :memberships, dependent: :destroy
  has_many :users, through: :memberships
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :memberships, dependent: :destroy
  has_many :projects, through: :memberships
  before_create :set_default_role

  def set_default_role
    self.role ||= 'user'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    before_action :authenticate_user!

    def index
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    before_action :authenticate_user!

    def index
        @assigned_projects = current_user.projects
        @other_projects = Project.where.not(id: @assigned_projects.pluck(:id))
    end

    def show
        @project = Project.find(params['id'])
    end

    def new
        @project = Project.new
    end

    def create
        @project = Project.new(permitted_params)
        if @project.save
            redirect_to project_path(@project)
        else
            render :new
        end
    end

    def edit
        @project = Project.find(params[:id])
    end

    def update
        @project = Project.find(params[:id])
        if @project.update(permitted_params)
          redirect_to project_path(@project), notice: 'Project updated successfully'
        else
          render :edit, alert: 'Unable to update the project'
        end
    end

    def destroy
        @project = Project.find(params['id'])
        @project.destroy
        redirect_to projects_path, notice: 'Project deleted'
    end

    protected

    def permitted_params
        params.require(:project).permit(:name, :description, user_ids: [])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user= User.find(params[:id])
  end
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path, notice: 'User deleted'
  end
  def update_role
    @user = User.find(params[:id])
  
    if @user.update(role: @user.role == 'admin' ? 'user' : 'admin')
      redirect_to user_path(@user), notice: "User role updated to #{@user.role}."
    else
      redirect_to user_path(@user), alert: 'Failed to update the user role.'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/home/index.html.haml
%div.flex-container{style: "display: flex; background-color: rgba(253, 253, 253, 0.4); text-align: center;flex-direction: column; padding: 1em; width: 35vw; border-radius:5px; margin-top:10px"}
    %h3 Welcome to Basecamp.
    %h3 A task managing application.
    %h3 Go to Projects or User menu    
%br
%div.flex-container{style: "display: flex; background-color: rgba(253, 253, 253, 0.4);justify-content: center; flex-direction: row; gap: 20px; padding: 1em; width: 35vw;border-radius:5px"}
    %h1= link_to "Projects", projects_path, style: 'background-color:  hsl(0, 0.00%, 12.20%) ; color: azure; padding: 5px; height:20px;border-radius: 3px;padding:10px'
    %h1=link_to "Users", users_path, style: 'background-color:  hsl(0, 0.00%, 12.20%); color: azure; padding: 5px; height:20px;border-radius: 3px;padding:10px; width 80px'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title= content_for(:title) || "My Basecamp 1"
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    %meta{:content => "yes", :name => "apple-mobile-web-app-capable"}/
    %meta{:content => "yes", :name => "mobile-web-app-capable"}/
    = csrf_meta_tags
    = csp_meta_tag
    = yield :head
    %link{href: "https://fonts.googleapis.com", rel: "preconnect"}/
    %link{crossorigin: "", href: "https://fonts.gstatic.com", rel: "preconnect"}/
    %link{href: "https://fonts.googleapis.com/css2?family=Asap+Condensed:wght@400&display=swap", rel: "stylesheet"}/
    %link{:href => "/icon.png", :rel => "icon", :type => "image/png"}/
    %link{:href => "/icon.svg", :rel => "icon", :type => "image/svg+xml"}/
    %link{:href => "/icon.png", :rel => "apple-touch-icon"}/
    = stylesheet_link_tag :app, "data-turbo-track": "reload"
    = javascript_importmap_tags
  %body
    - if user_signed_in?
      %header
        =link_to (image_tag "https://i.ibb.co/jHkFS5S/logo.png", style: "width: 300px; height: auto; border-radius: 15px;margin-top: 10px"), root_path
        %nav.navbar
          %ul
            %li= link_to "Home", root_path
            %li= link_to "Projects", projects_path
            %li= link_to "Users", users_path
            %li= link_to "Log Out", destroy_user_session_path, method: :delete
    = yield

app/views/projects/edit.html.haml
= simple_form_for @project do |f|
  %div.projects-container{style:"background-color: rgba(253, 253, 253, 0.4);"}
    %div.field
      = f.label :name
      = f.input :name, label: false

    %div.field
      = f.label :description
      = f.input :description, label: false

    %div.field
      %strong Assign Users:
      %ul.user-list
        - User.all.each do |user|
          %li
            = f.check_box :user_ids, { multiple: true, checked: @project.user_ids.include?(user.id) }, user.id, nil
            = user.email

    %div.actions
      = f.submit "Update Project"

app/views/projects/index.html.haml
%div.flex-container{style: "display: flex; gap: 20px"}
  %div.projects-container{style:"background-color: rgba(253, 253, 253, 0.4);"}
    %h2 My Projects
    %ul.projects-list
      - @assigned_projects.each do |project|
        %li.project-item
          = link_to project.name, project_path(project)
        %br

  %div.projects-container{style:"background-color: rgba(253, 253, 253, 0.4);"}
    %h2 Other Projects
    %ul.projects-list
      - @other_projects.each do |project|
        %li.project-item
          = link_to project.name, project_path(project)
        %br
%br   
%div.navbar
  %ul
    %li= link_to "New Project", new_project_path

app/views/projects/new.html.haml
= simple_form_for @project do |f|
  %div.projects-container{style:"background-color: rgba(253, 253, 253, 0.4);"}
    %div.field
      = f.label :name
      = f.input :name, label: false

    %div.field
      = f.label :description
      = f.input :description, label: false

    %div.field
      %strong Assign Users:
      %ul.user-list
        - User.all.each do |user|
          %li
            = f.check_box :user_ids, { multiple: true }, user.id, nil
            = user.email

    %div.actions
      = f.submit "Create Project"

app/views/projects/show.html.haml
%div.flex-container{style: "display: flex; flex-direction: column; gap: 20px; padding: 1em"}
    %div.projects-container{style:"background-color: rgba(253, 253, 253, 0.4);"}
        %h3 Project name:
        = @project.name
        %br
        %h3 Project description:
        = @project.description
        %br
        %h3 Project assigned to:
        - @project.memberships.each do |membership|
            %div
                = membership.user.email
                = "(#{membership.role})" if membership.role.present?
        %br
    = link_to "Edit this project", edit_project_path, data: { confirm: 'This will edit the project. Are you sure?' }, style: 'background-color: rgb(40, 40, 41); color: azure; padding: 5px; height:20px;border-radius: 3px;padding:10px'
    = link_to 'Delete this project', project_path(@project), method: :delete, data: { confirm: 'This will delete the project. Are you sure?' }, style: 'background-color: rgb(75, 22, 13); color: azure; padding: 5px; height:20px;border-radius: 3px;padding:10px'
    

app/views/users/index.html.haml
.user-info{style: "flex: 1;"}
  %h2 Welcome to User menu
  - if current_user
    %h3= "Your email is: #{current_user.email}"
    %h3= "Your role is: #{current_user.role}"
    = link_to 'Delete this user', 
              users_path(current_user), 
              method: :delete, 
              data: { confirm: 'This will delete your user. Are you sure?' }, 
              style: 'background-color: rgb(40, 40, 41); color: azure; padding: 5px; height:20px;border-radius: 3px;padding:10px'
    = link_to 'Change your user Role', 
              update_role_user_path(current_user), 
              method: :patch, 
              style: 'background-color: rgb(75, 22, 13); color: azure; padding: 5px; height:20px;border-radius: 3px;padding:10px', 
              onclick: 'setTimeout(function(){ location.reload(); }, 500);'

.admin-info{style: "flex: 1;"}
  - if current_user.role == "admin"
    .projects-container{style: "background-color: rgba(253, 253, 253, 0.4);"}
      %h3 As an admin, you can delete users:
      - User.all.each do |user|
        %p
          %b= user.email
          - if user != current_user
            = link_to 'Delete this user', 
                      user_path(user), 
                      method: :delete, 
                      data: { confirm: 'This will delete this user. Are you sure?' }, 
                      style: 'background-color: rgb(40, 40, 41); color: azure; padding: 2px; height:10px;border-radius: 3px;padding:5px'